from pathlib import Path
import streamlit as st
from PIL import Image

# -- Path settings
current_dir = Path(__file__).parent if "__file__" in locals() else Path.cwd()
css_file = current_dir / "styles" / "main.css"
resume_file = current_dir / "assets" / "CV.pdf"
profile_pic = current_dir / "assets" / "profile_pic.png"

#general settings

PAGE_TITLE = "Digital CV | Victor Augusto"
PAGE_ICON = ":wave:"
NAME = "Victor Augusto"
DESCRIPTION = """
A Computer Engineering graduate from UNIVASF, with a strong background in embedded systems, recently enhanced 
by a completed Specialization in Software Development for the Automotive Industry from UFPE.
 Passionate about data analysis, software development using C/C++ and Python.
 My specialization provided in-depth knowledge of embedded systems, automotive networks (CAN, LIN, Ethernet), 
 AUTOSAR, RTOS, and software validation.
"""
EMAIL = "victoraugusto1950@hotmail.com"
SOCIAL_MEDIA = {
    "LinkedIn": "https://www.linkedin.com/in/victorabalbino/",
    "GitHub": "https://github.com/victorltd",
    "YouTube": "https://www.youtube.com/@victoraugustoimg"
}
PROJECTS = {
    "🛰️ Weather Station for Aerodesign Competition": {
        "description": "An application where competitors of Aerodesign Competition could see meteorological data. Designed and developed in HTML, CSS and Javascripts, and uses ESP8266 and BMP280 as sensor; The backend was implemented on Google Firebase. The site was tested on the 2022 Aerodesign Competition. This project was used as my bachelor thesis.", #
        "github_url": "https://github.com/victorltd/TCC" # Exemplo, substitua pelo seu link real
    },
    "📡 Telemetry System for Aerodesign (F-Carranca)": {
        "description": "Assembly and implementation of embedded telemetry, and thus, obtained data in flight with the use of Arduino, ESP32 and the Pixhawk flight controller, after which processed the data and passed on the information obtained to the other sectors. The information generated by telemetry helped to increase the score of the technical report of the sectors that depended on them.", #
        "github_url": "https://github.com/victorltd/TCC" # Exemplo, substitua pelo seu link real
    },
    "📊 Brazilian Federal Highway (BR) Accident Analysis with Streamlit": {
        "description": "Developed an interactive Streamlit dashboard to analyze open data from the PRF (Brazilian Federal Highway Police) regarding accidents on national highways (BRs). The primary objective was to identify patterns, critical accident-prone locations, and common contributing factors (e.g., types of accidents, causes, conditions of victims, vehicle types involved, and temporal trends). By processing and visualizing this data, the project aimed to provide actionable insights that could contribute to public awareness campaigns, support data-driven decision-making for road safety interventions, and potentially guide infrastructure improvements.",
        "github_url": "https://github.com/victorltd/Streamlit_PRF" # Substitua pelo seu link real
    }
}

st.set_page_config(page_title=PAGE_TITLE, page_icon=PAGE_ICON)

#st.title("Hello there")

with open(css_file) as f:
    st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)   
with open (resume_file, "rb") as file:
    PDFbyte = file.read()
profile_pic = Image.open(profile_pic)

#hero section
col1, col2 = st.columns(2, gap="small")
with col1:
    st.image(profile_pic, width=230)

with col2:
    st.title(NAME)
    st.write(DESCRIPTION)
    st.download_button(label="Download Resume",
                       data=PDFbyte,
                       file_name=resume_file.name,
                       mime="application/octet-stream",
    ) 
    st.write(f"Email: {EMAIL}")


#social links
st.write("#")
cols = st.columns(len(SOCIAL_MEDIA))
for index , (platform, link) in enumerate(SOCIAL_MEDIA.items()):
    with cols[index]:
        st.markdown(f"[{platform}]({link})")

# --- EDUCATION ---
st.write("#") # Adiciona um espaço
st.subheader("Education")
st.write("---") # Adiciona uma linha divisória


# UFPE
st.write("🎓", "**Specialization in software development for the automotive industry**") # [cite: 1]
st.write("*Federal University Pernambuco (UFPE)*") # [cite: 1]
st.write("October 2024 – May 2025") # [cite: 1]
st.write(
    """
    - Focus on embedded systems, automotive networks (CAN, LIN, Ethernet), AUTOSAR, RTOS, and software validation.
    - Includes programming in C/C++, configuration management, and software testing for the automotive industry. 
    """
)
st.write("") # Adiciona um pequeno espaço

# UNIVASF
st.write("🎓", "**Bachelor of Science in Computer Engineering**") # [cite: 1]
st.write("*Federal University of Vale do São Francisco (UNIVASF)*") # [cite: 1]
st.write("November 2017 – June 2024") # [cite: 1]




#experience

st.write("#")
st.subheader("Experience & Qualifications")
st.write("---") # Adiciona uma linha divisória

st.write (
    """
    - ✅ 2 years of internship at Embraer working with data analisys and software development
    - ✅ Great experience with Power Platform, SQL, and data visualization tools, such as Power BI
    - ✅ Good understanding of statistical principles and their application
    - ✅ Excellent team player, display strong communication skills and sense of initiative on tasks
    """
)

# --- SKILLS ---
st.write("#")
st.subheader("Hard Skills & Technologies") #  
st.write("---") # Adiciona uma linha divisória
st.write(
    """
    - 💻 **Programming Languages:** Python, C/C++, SQL, Matlab, HTML, CSS, JS
    - 📊 **Data Visualization & Automation:** Power BI, Power Apps, Power Automate  
    - 📡 **Embedded Systems & IoT:** Arduino, ESP32, ESP8266 (mentioned in project context) 
    - ⚙️ **Engineering & Simulation:** Matlab, Simulink  
    - 🗄️ **Database & Backend:** Firebase, SQL  
    - 🛠️ **Development & Version Control:** Jupyter Notebook, Git  
    - 📂 **Office Suite:** Office 365, Excel  
    - 🚗 **Automotive Standards & Protocols:** CAN, LIN, Ethernet, AUTOSAR, RTOS (from UFPE specialization) 
"""
)

st.write("#")
st.subheader("Soft Skills") 
st.write("---") # Adiciona uma linha divisória
st.write(
    """
    - ⏱️ Time management  
    - 🔍 Systems Thinking  
    - 💡 Emotional Intelligence  
    - 🧩 Problem Solving  
    - 🤝 Conflict resolution  
    - 🗣️ Negotiation  
    """
)

#work history
st.write("#")
st.subheader("Work History")
st.write("---")

st.write("✈️", "**PMO Intern | Embraer Commercial Aviation**")
st.write("2023 - 2024")
st.write(
    """
    - ▶️ Intern of PMO in Programs Directory of Embraer Commercial Aviation
    - ▶️ Develop digital solutions using Microsoft tools (PowerApps, PowerBI, Automate) to optimize processes and improve data management and conduct training on technological trends for the Program Management team;
    - ▶️ Created interactive dashboards in PowerBI, consolidating data from different sources, enabling real-time analysis of key indicators in the area. Developed applications in PowerApps to automate tasks such as skills assessment, freeing up time for strategic activities.
    - ▶️ Increased data visibility, facilitating data-driven decision making. Reduced task processing time, increasing team productivity. Team with greater knowledge of technological trends, preparing the company for the future.
    """
)

st.write("#")
st.subheader("Extra Curricular Activities")
st.write("---")

st.write("✈️", "**Member of Electrical Project  | F-Carranca Aerodesign Team**")
st.write("2018 - 2022")
st.write(
    """
    - ▶️ Member of Electrical Project Sector and later on Performance Analysis;
    - ▶️ Responsible for dimensioning all electrical components of the aircraft and in-flight data acquisition;
    - ▶️ Assembly and implementation of embedded telemetry, and thus, obtained data in flight with the use of Arduino and the Pixhawk flight controller, after which processed the data and passed on the information obtained to the other sectors.
    - ▶️ The information generated by telemetry helped to increase the score of the technical report of the sectors that depended on them. The team reached the 2nd overall position in Design Score, winning the flight stage and being Champion.
    """
)

st.write("") # Adiciona um pequeno espaço

st.write("📓", "**Researcher  | Federal University of Vale do São Francisco**")
st.write("2018 - 2022")
st.write(
    """
    - ▶️ Student researcher with a project funded by FABESP(Bahia Research Support Foundation)
    - ▶️ Conduct research on the impact of digital games and their influences on children's physical health
    """
)

# --- PROJECTS & ACCOMPLISHMENTS ---
st.write("#")
st.markdown("<div id='projects_anchor'></div>", unsafe_allow_html=True) # Sua âncora, se estiver usando
st.subheader("Projects & Accomplishments")
st.write("---")

for project_name, project_details in PROJECTS.items():
    st.write(f"🚀 **{project_name}**")
    st.write(project_details["description"])
    if project_details.get("github_url") and project_details["github_url"] != "": # Verifica se o link existe e não está vazio
        st.markdown(f"[View on GitHub]({project_details['github_url']})")
    st.write("---") # Adiciona uma pequena divisória entre os projetos, opcional