from pathlib import Path
import streamlit as st
from PIL import Image

# -- Path settings
current_dir = Path(__file__).parent if "__file__" in locals() else Path.cwd()
css_file = current_dir / "styles" / "main.css"
resume_file = current_dir / "assets" / "CV.pdf"
profile_pic = current_dir / "assets" / "profile_pic.png"

#general settings

PAGE_TITLE = "Digital CV | Victor Augusto"
PAGE_ICON = ":wave:"
NAME = "Victor Augusto"
DESCRIPTION = """
Fresh Computer Enginner graduate with a passion for data analisys and airplanes.
"""
EMAIL = "victoraugusto1950@hotmail.com"
SOCIAL_MEDIA = {
    "LinkedIn": "https://www.linkedin.com/in/victor-augusto-1a1a1a1a/",
    "GitHub": "AAugusto1950",
    "YouTube": "https://www.youtube.com/channel/UC"
}
PROJECTS = {
    "Estação Meteorológica do Aerodesign": "Descrição do projeto 1",
    "Sistema de Telemetria para Aerodesign": "Descrição do projeto 2",
}

st.set_page_config(page_title=PAGE_TITLE, page_icon=PAGE_ICON)

st.title("Hello there")

with open(css_file) as f:
    st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)   
with open (resume_file, "rb") as file:
    PDFbyte = file.read()
profile_pic = Image.open(profile_pic)

#hero section
col1, col2 = st.columns(2, gap="small")
with col1:
    st.image(profile_pic, width=230)

with col2:
    st.title(NAME)
    st.write(DESCRIPTION)
    st.download_button(label="Download Resume",
                       data=PDFbyte,
                       file_name=resume_file.name,
                       mime="application/octet-stream",
    ) 
    st.write(f"Email: {EMAIL}")


#social links
st.write("#")
cols = st.columns(len(SOCIAL_MEDIA))
for index , (platform, link) in enumerate(SOCIAL_MEDIA.items()):
    with cols[index]:
        st.markdown(f"[{platform}]({link})")

#experience

st.write("#")
st.subheader("Experience & Qualifications")
st.write (
    """
    - ✅ 2 years of internship at Embraer working with data analisys and software development
    - ✅ Great experience with Power Platform, SQL, and data visualization tools, such as Power BI
    - ✅ Good understanding of statistical principles and their application
    - ✅ Excellent team player, display strong communication skills and sense of initiative on tasks
    """
)

#skills
st.write("#")
st.subheader("Hard Skills")
st.write(
    """
    - Data Visualization and Automation: Power BI, PowerApps, Power Automate.
    - Programming Languages: Python, MATLAB, HTML, CSS, JavaScript, SQL.
    - Embedded Systems and IoT: Arduino, ESP32, ESP8266.
    - Engineering and Simulation Tools: MATLAB, Simulink.
    - Database Management and Backend Development: Firebase, Jupyter Notebook, Git
"""
)

#work history
st.write("#")
st.subheader("Work History")
st.write("---")

st.write("✈️", "**PMO Intern | Embraer Commercial Aviation**")
st.write("2023 - 2024")
st.write(
    """
    - ▶️ Intern of PMO in Programs Directory of Embraer Commercial Aviation
    - ▶️ Develop digital solutions using Microsoft tools (PowerApps, PowerBI, Automate) to optimize processes and improve data management and conduct training on technological trends for the Program Management team;
    - ▶️ Created interactive dashboards in PowerBI, consolidating data from different sources, enabling real-time analysis of key indicators in the area. Developed applications in PowerApps to automate tasks such as skills assessment, freeing up time for strategic activities.
    - ▶️ Increased data visibility, facilitating data-driven decision making. Reduced task processing time, increasing team productivity. Team with greater knowledge of technological trends, preparing the company for the future.
    """
)

st.write("#")
st.subheader("Extra Curricular Activities")
st.write("---")

st.write("✈️", "**Member of Electrical Project  | F-Carranca Aerodesign Team**")
st.write("2018 - 2022")
st.write(
    """
    - ▶️ Member of Electrical Project Sector and later on Performance Analysis;
    - ▶️ Responsible for dimensioning all electrical components of the aircraft and in-flight data acquisition;
    - ▶️ Assembly and implementation of embedded telemetry, and thus, obtained data in flight with the use of Arduino and the Pixhawk flight controller, after which processed the data and passed on the information obtained to the other sectors.
    - ▶️ The information generated by telemetry helped to increase the score of the technical report of the sectors that depended on them. The team reached the 2nd overall position in Design Score, winning the flight stage and being Champion.
    """
)

st.write("📓", "**Researcher  | Federal University of Vale do São Francisco**")
st.write("2018 - 2022")
st.write(
    """
    - ▶️ Student researcher with a project funded by FABESP(Bahia Research Support Foundation)
    - ▶️ Conduct research on the impact of digital games and their influences on children's physical health
    """
)

#projects
st.write("#")
st.subheader("Projects & Accomplishments") 
st.write("---")
for project, description in PROJECTS.items():
    st.write(f"🚀 **{project}**: {description}")
